source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
pod 'AFNetworking’
pod 'MJRefresh’
pod 'SDWebImage’
pod 'Masonry’
pod 'JSONModel’
pod 'MBProgressHUD’
pod 'Toast’
pod 'UIAlertView+Blocks’
pod 'UIActionSheet+Blocks’
pod 'UMengAnalytics’, ‘4.1.0’
pod 'JSONKit-NoWarning'
pod 'IQKeyboardManager’
pod 'BmobSDK'
